---
title: "Approximating error in Kernel Deconvolution Methods"
author: "Guillermo Basulto-Elias"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Consider the panel data 
$$
\begin{matrix}
Y_{11} & \cdots & Y_{1k} \\
Y_{21} & \cdots & Y_{2k} \\
\vdots & \ddots & \vdots \\
Y_{n1} & \cdots & Y_{nk}
\end{matrix},
$$
where $Y_{ij} = X_i + \epsilon_{ij}$. We want to approximate the charactestic function of the error, $\phi_{\epsilon}(\cdot)$ based on these data. 

Recall that $Y_{ij_1} - Y_{ij_2} = \epsilon_{ij_1} - \epsilon_{ij_2}$, that is, it is possible of extract differences of errors by taking differences of observations for the same individual. In vignette _differences_, we describe three possible ways to do this using the function `process_differences()`. Let $L$ denote the number of differences (thus, $L = nk(k - 1)/2$, $n(k - 1)$ or $n\lfloor k\rfloor/2$). Let $\delta_1, \ldots, \delta_L$ be such differences.

## Nonparametric approach

Assume that the error distribution is symmetric and its characteristic function is never zero. The latter condition is true is $\boldsymbol{\epsilon}$ is Laplace or normal, for instance. Then $\phi_{\boldsymbol{\delta}}(\boldsymbol{t}) = 
  \phi_{\boldsymbol{\epsilon}}^2(\boldsymbol{t})$

$$
\hat{\phi}_{\epsilon}(t) = 
\sqrt{\lvert \hat{\phi}_{\boldsymbol{\delta}} (\boldsymbol{t}) \rvert}
$$

Therefore, 
$$
\hat{\phi}_{\bar{\epsilon}}(t) =
\left[\hat{\phi}_{\epsilon}(t/k)\right]^k
$$

```{r, fig.width= 8, fig.height= 6}
library(kerdec)

n <- 50
k <- 4
smp <- matrix(rnorm(n*k), n, k)
t <- seq(-10, 10, .05)

averaged_smp <- rowMeans(smp);

ecf1 <- ecf_mod(t, averaged_smp)
ecf2 <- error_cf_approx(t = t, smp = smp, diff_method = 1)
ecf3 <- exp(-t^2/2/k)

plot(range(t), range(c(ecf1, ecf2, ecf3)), type = "n", col = "green")
lines(t, ecf1, col = "green")
lines(t, ecf2, col = "blue")
lines(t, ecf3, col = "red")

```

