---
title: "Kernel Density Deconvolution"
author: "Guillermo Basulto-Elias"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

It is desired to provide a nonparametric density estimator of a random vector $\boldsymbol{X}$ a random vector in $\mathbb{R}^d$ based on samples contaminated with additive error $\boldsymbol{\epsilon}$ say
$$\boldsymbol{Y} = \boldsymbol{X} + \boldsymbol{\epsilon}$$.


Let $\boldsymbol{X}_1, \ldots, \boldsymbol{X}_n$ be a sample of independent and identically distributed (_iid_) random vectors in $\mathbb{R}^d$. Suppose that it is desired to provide a density estimator 

where for $i = 1, \ldots, n$,
$$\boldsymbol{Y}_i = \boldsymbol{X}_i + \boldsymbol{\epsilon}_i$$. 

Kernel deconvolution formula.

$$
\hat{f}_{\boldsymbol{X}}(\boldsymbol{x}) = 
    \frac{1}{(2\pi)^d}
    \int e^{-\imath \langle \boldsymbol{x}, \boldsymbol{t} \rangle}
    \hat{\phi}_{\boldsymbol{Y}, n}(\boldsymbol{t})
    \frac{K^{Ft}(H^{-1/2}\boldsymbol{t})}
         {\hat{\phi}_{\boldsymbol{\epsilon}}(\boldsymbol{t})}
    d\boldsymbol{t}
$$

## Kernel deconvolution density estimation on panel data

Information about the error distribution can be extracted from panel data by taking differences or observations for the same individual, which produces differences of errors. For example, if $Y_{ij_1} = X_i + \epsilon_{ij_1}$ and $Y_{ij_2} = X_i + \epsilon_{ij_2}$ are two observations with measurement error for the same individual, then $Y_{ij_1} - Y_{ij_2} = \epsilon_{ij_1} - \epsilon_{ij_2}$.

If there are only two observations per individual, this process is as simple as taking the difference between these two. However, when there are more than two observations per individual, there is not a unique way to do this. It is possible to take all possible differences, resulting on a sample of non-independent differences; to obtain independent samples, although fewer differences would be available, or a compromise between them.

The function `process_differences()` considers three approaches which are described below. For the examples, consider a panel data array of contaminated observations with $n$ individuals and every measurement taken $l$ times, that is, 
$$
\begin{matrix}
Y_{11} & \cdots & Y_{1k} \\
Y_{21} & \cdots & Y_{2k} \\
\vdots & \ddots & \vdots \\
Y_{n1} & \cdots & Y_{nk}
\end{matrix}.
$$


```{r}
library(kerdec)

kerdec_dens_panel_1d_cpp(matrix(rnorm(12), 3, 4), h = .5, lower = -2, upper = 2,
                         resolution = 64, ker = 1)

```

