// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __kerdec_h__
#define __kerdec_h__

#include "kerdec_RcppExports.h"

#endif // __kerdec_h__
