// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ft_kernel_cpp
arma::vec ft_kernel_cpp(const arma::mat& t, int ker);
RcppExport SEXP kerdec_ft_kernel_cpp(SEXP tSEXP, SEXP kerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type ker(kerSEXP);
    rcpp_result_gen = Rcpp::wrap(ft_kernel_cpp(t, ker));
    return rcpp_result_gen;
END_RCPP
}
// ecf_re_cpp
arma::vec ecf_re_cpp(const arma::mat& t, const arma::mat& smp);
RcppExport SEXP kerdec_ecf_re_cpp(SEXP tSEXP, SEXP smpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type smp(smpSEXP);
    rcpp_result_gen = Rcpp::wrap(ecf_re_cpp(t, smp));
    return rcpp_result_gen;
END_RCPP
}
// ecf_im_cpp
arma::vec ecf_im_cpp(const arma::mat& t, const arma::mat& smp);
RcppExport SEXP kerdec_ecf_im_cpp(SEXP tSEXP, SEXP smpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type smp(smpSEXP);
    rcpp_result_gen = Rcpp::wrap(ecf_im_cpp(t, smp));
    return rcpp_result_gen;
END_RCPP
}
// ecf_mod_cpp
arma::vec ecf_mod_cpp(const arma::mat& t, const arma::mat& smp);
RcppExport SEXP kerdec_ecf_mod_cpp(SEXP tSEXP, SEXP smpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type smp(smpSEXP);
    rcpp_result_gen = Rcpp::wrap(ecf_mod_cpp(t, smp));
    return rcpp_result_gen;
END_RCPP
}
// ecf_cpp
arma::cx_vec ecf_cpp(const arma::mat& t, const arma::mat& smp);
RcppExport SEXP kerdec_ecf_cpp(SEXP tSEXP, SEXP smpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type smp(smpSEXP);
    rcpp_result_gen = Rcpp::wrap(ecf_cpp(t, smp));
    return rcpp_result_gen;
END_RCPP
}
// process_differences_cpp
arma::vec process_differences_cpp(const arma::mat& smp, int method);
RcppExport SEXP kerdec_process_differences_cpp(SEXP smpSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type smp(smpSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(process_differences_cpp(smp, method));
    return rcpp_result_gen;
END_RCPP
}
// kerdec_dens_cpp
arma::cx_vec kerdec_dens_cpp(const arma::vec& smp, const arma::vec& error_smp, double h, double lower, double upper, int resolution, int ker, double sigma, int k, int error_dist, int panel_proc, double cutoff);
RcppExport SEXP kerdec_kerdec_dens_cpp(SEXP smpSEXP, SEXP error_smpSEXP, SEXP hSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP resolutionSEXP, SEXP kerSEXP, SEXP sigmaSEXP, SEXP kSEXP, SEXP error_distSEXP, SEXP panel_procSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type smp(smpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type error_smp(error_smpSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type ker(kerSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type error_dist(error_distSEXP);
    Rcpp::traits::input_parameter< int >::type panel_proc(panel_procSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(kerdec_dens_cpp(smp, error_smp, h, lower, upper, resolution, ker, sigma, k, error_dist, panel_proc, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// kerdec_dens_nonreg_cpp
arma::cx_vec kerdec_dens_nonreg_cpp(const arma::vec& smp, const arma::vec& error_smp, double h, const arma::vec& x_eval, int resolution, int ker, double sigma, int k, int error_dist, int panel_proc, double cutoff);
RcppExport SEXP kerdec_kerdec_dens_nonreg_cpp(SEXP smpSEXP, SEXP error_smpSEXP, SEXP hSEXP, SEXP x_evalSEXP, SEXP resolutionSEXP, SEXP kerSEXP, SEXP sigmaSEXP, SEXP kSEXP, SEXP error_distSEXP, SEXP panel_procSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type smp(smpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type error_smp(error_smpSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x_eval(x_evalSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type ker(kerSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type error_dist(error_distSEXP);
    Rcpp::traits::input_parameter< int >::type panel_proc(panel_procSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(kerdec_dens_nonreg_cpp(smp, error_smp, h, x_eval, resolution, ker, sigma, k, error_dist, panel_proc, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// amise
double amise(double h, double mu2K2, double R, const arma::vec& error_smp, int resolution, int ker, int n, double sigma, int k, int error_dist, int panel_proc);
RcppExport SEXP kerdec_amise(SEXP hSEXP, SEXP mu2K2SEXP, SEXP RSEXP, SEXP error_smpSEXP, SEXP resolutionSEXP, SEXP kerSEXP, SEXP nSEXP, SEXP sigmaSEXP, SEXP kSEXP, SEXP error_distSEXP, SEXP panel_procSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type mu2K2(mu2K2SEXP);
    Rcpp::traits::input_parameter< double >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type error_smp(error_smpSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type ker(kerSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type error_dist(error_distSEXP);
    Rcpp::traits::input_parameter< int >::type panel_proc(panel_procSEXP);
    rcpp_result_gen = Rcpp::wrap(amise(h, mu2K2, R, error_smp, resolution, ker, n, sigma, k, error_dist, panel_proc));
    return rcpp_result_gen;
END_RCPP
}
// CV
double CV(double h, const arma::vec& Z, const arma::vec& smp, const arma::vec& error_smp, int resolution, int ker, double sigma, int k, int error_dist, int panel_proc, double cutoff);
RcppExport SEXP kerdec_CV(SEXP hSEXP, SEXP ZSEXP, SEXP smpSEXP, SEXP error_smpSEXP, SEXP resolutionSEXP, SEXP kerSEXP, SEXP sigmaSEXP, SEXP kSEXP, SEXP error_distSEXP, SEXP panel_procSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type smp(smpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type error_smp(error_smpSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type ker(kerSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type error_dist(error_distSEXP);
    Rcpp::traits::input_parameter< int >::type panel_proc(panel_procSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(CV(h, Z, smp, error_smp, resolution, ker, sigma, k, error_dist, panel_proc, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// kerdec_dens2D_cpp
arma::cx_mat kerdec_dens2D_cpp(const arma::mat& smp, const arma::mat& error_smp, double h, const arma::vec& lower, const arma::vec& upper, const arma::vec& resolution, int ker, const arma::vec& sigma, int k, int error_dist, int panel_proc, double cutoff);
RcppExport SEXP kerdec_kerdec_dens2D_cpp(SEXP smpSEXP, SEXP error_smpSEXP, SEXP hSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP resolutionSEXP, SEXP kerSEXP, SEXP sigmaSEXP, SEXP kSEXP, SEXP error_distSEXP, SEXP panel_procSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type smp(smpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type error_smp(error_smpSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type ker(kerSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type error_dist(error_distSEXP);
    Rcpp::traits::input_parameter< int >::type panel_proc(panel_procSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(kerdec_dens2D_cpp(smp, error_smp, h, lower, upper, resolution, ker, sigma, k, error_dist, panel_proc, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// CV2D
double CV2D(double h, const arma::vec& Z, const arma::vec& smp, const arma::vec& error_smp, int resolution, int ker, double sigma, int k, int error_dist, int panel_proc, double cutoff);
RcppExport SEXP kerdec_CV2D(SEXP hSEXP, SEXP ZSEXP, SEXP smpSEXP, SEXP error_smpSEXP, SEXP resolutionSEXP, SEXP kerSEXP, SEXP sigmaSEXP, SEXP kSEXP, SEXP error_distSEXP, SEXP panel_procSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type smp(smpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type error_smp(error_smpSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type ker(kerSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type error_dist(error_distSEXP);
    Rcpp::traits::input_parameter< int >::type panel_proc(panel_procSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(CV2D(h, Z, smp, error_smp, resolution, ker, sigma, k, error_dist, panel_proc, cutoff));
    return rcpp_result_gen;
END_RCPP
}
