// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ecf_re_cpp
arma::vec ecf_re_cpp(arma::mat t, arma::mat smp);
RcppExport SEXP kerdec_ecf_re_cpp(SEXP tSEXP, SEXP smpSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type smp(smpSEXP);
    __result = Rcpp::wrap(ecf_re_cpp(t, smp));
    return __result;
END_RCPP
}
// ecf_im_cpp
arma::vec ecf_im_cpp(arma::mat t, arma::mat smp);
RcppExport SEXP kerdec_ecf_im_cpp(SEXP tSEXP, SEXP smpSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type smp(smpSEXP);
    __result = Rcpp::wrap(ecf_im_cpp(t, smp));
    return __result;
END_RCPP
}
// ecf_mod_cpp
arma::vec ecf_mod_cpp(arma::mat t, arma::mat smp);
RcppExport SEXP kerdec_ecf_mod_cpp(SEXP tSEXP, SEXP smpSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type smp(smpSEXP);
    __result = Rcpp::wrap(ecf_mod_cpp(t, smp));
    return __result;
END_RCPP
}
// ecf_cpp
arma::cx_vec ecf_cpp(arma::mat t, arma::mat smp);
RcppExport SEXP kerdec_ecf_cpp(SEXP tSEXP, SEXP smpSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type smp(smpSEXP);
    __result = Rcpp::wrap(ecf_cpp(t, smp));
    return __result;
END_RCPP
}
// FT_ker
double FT_ker(double t, int ker);
RcppExport SEXP kerdec_FT_ker(SEXP tSEXP, SEXP kerSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type ker(kerSEXP);
    __result = Rcpp::wrap(FT_ker(t, ker));
    return __result;
END_RCPP
}
