// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ecf_mod_1d
NumericVector ecf_mod_1d(NumericVector t, NumericVector smp);
RcppExport SEXP kerdec_ecf_mod_1d(SEXP tSEXP, SEXP smpSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type smp(smpSEXP);
    __result = Rcpp::wrap(ecf_mod_1d(t, smp));
    return __result;
END_RCPP
}
