# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Real part of empirical characteristic function
#'
#' Real part of empirical characteristic function of a d-dimensional
#' random variable. This function is evaluated at m vectors of size
#' d.
#'
#' This function must receive matrices. Vectors or values are not
#' accepted.
#' 
#' @param t mxd matrix where the function will be evaluated.
#' @param smp nxd matrix with sample size if size n.
#'
#' @return A vector of size m with the real part of the empirical
#' characteristic function.
#'
#' @export
ecf_re <- function(t, smp) {
    .Call('kerdec_ecf_re', PACKAGE = 'kerdec', t, smp)
}

#' Imaginary part of empirical characteristic function
#'
#' Imaginary part of empirical characteristic function of a
#' d-dimensional random variable. This function is evaluated at m
#' vectors of size d.
#'
#' This function must receive matrices. Vectors or values are not
#' accepted.
#' 
#' @param t mxd matrix where the function will be evaluated.
#' @param smp nxd matrix with sample size if size n.
#'
#' @return A vector of size m with the imaginary part of the
#' empirical characteristic function.
#'
#' @export
ecf_im <- function(t, smp) {
    .Call('kerdec_ecf_im', PACKAGE = 'kerdec', t, smp)
}

